version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - nilerr
    - nolintlint
    - reassign
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintln
        - fmt.Fprintf

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
